<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>finalAdvice</name>
  <uuid>3505db4c-9992-4a41-9a63-2b984bccf3ca</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to name + " ... " + weatheradvice ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
