<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>storm</name>
  <uuid>142f8baf-477a-4ec2-afa6-1848a202ed0d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	weather is storm alert
then
	set decision to "Stay home! There is a storm alert" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
