<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Join</name>
  <uuid>f197d208-6aec-4d2f-90f7-4530e7d3eae4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to Name + " ... " + 'Decision 2' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
